name: test-build

on: [push]

jobs:
  test-build:
    strategy:
      matrix:
        node-version: [20, 22]
    runs-on: ubuntu-latest
    container: node:${{matrix.node-version}}-alpine
    name: With Node.js ${{matrix.node-version}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Format
        run: npm run format
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
